# Generated by Django 4.2.18 on 2025-05-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_perfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('STAFF', 'Personal de la Fundación'), ('USER', 'Usuario')], default='USER', max_length=10, verbose_name='Rol'),
        ),
    ]
