# Generated by Django 4.2.18 on 2025-05-28 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='attendance_managers',
            field=models.ManyToManyField(blank=True, related_name='managed_activities', to=settings.AUTH_USER_MODEL, verbose_name='Gestores de Asistencia'),
        ),
    ]
